### ISSUE TITLE
New keywords for `retrieve_jij_files` crash `gf_writeout` workflow

### ISSUE THREAD

**Issue by fBert31** [JuDFTteam/aiida-kkr#14]
When running the `gf_writeout` workflow for the latest `develop` branch it crashes since the keywords `JIJRAD`, `JIJRADXY`, `JIJSITEI`, `JIJSITEJ` from `masci_tools/io/kkr_params.py` raise a `KeyError` in the `update_params_wf` from `aiida_kkr.tools.common_workfunctions`. Possibly, this error will also occur in other workflows. 

The error message for the `gf_writeout` workflow looks like this:

```
12/04/2018 10:38:02 AM <5320> aiida.orm.implementation.general.calculation.work.WorkCalculation: [REPORT] [19633|kkr_flex_wc|on_except]: Traceback (most recent call last):
  File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/process_states.py", line 228, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/Users/bert/sourcecodes/github/aiida_core/aiida/work/workchain.py", line 158, in _do_step
    finished, stepper_result = self._stepper.step()
  File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/workchains.py", line 292, in step
    finished, result = self._child_stepper.step()
  File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/workchains.py", line 430, in step
    finished, retval = self._child_stepper.step()
  File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/workchains.py", line 292, in step
    finished, result = self._child_stepper.step()
  File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/workchains.py", line 242, in step
    return True, self._fn(self._workchain)
  File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/aiida_kkr/workflows/gf_writeout.py", line 271, in set_params_flex
    paranode_flex = update_params_wf(self.ctx.input_params_KKR, updatenode)
  File "/Users/bert/sourcecodes/github/aiida_core/aiida/work/workfunctions.py", line 76, in wrapped_function
    result, _ = run_get_node(*args, **kwargs)
  File "/Users/bert/sourcecodes/github/aiida_core/aiida/work/workfunctions.py", line 69, in run_get_node
    return proc.execute(), proc.calc
  File "/Users/bert/sourcecodes/github/aiida_core/aiida/work/processes.py", line 742, in execute
    result = super(FunctionProcess, self).execute()
  File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/processes.py", line 992, in execute
    return self.future().result()
  File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/kiwipy/futures.py", line 43, in result
    return super(Future, self).result(timeout=0.)
  File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/process_states.py", line 228, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/processes.py", line 981, in run
    return self._run()
  File "/Users/bert/sourcecodes/github/aiida_core/aiida/work/processes.py", line 776, in _run
    result = self._func(*args, **kwargs)
  File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/aiida_kkr/tools/common_workfunctions.py", line 54, in update_params_wf
    nodedesc=nodedesc, **updatenode_dict)
  File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/aiida_kkr/tools/common_workfunctions.py", line 106, in update_params
    if kwargs[key] != inp_params[key]:
KeyError: u'JIJSITEJ'
```

**Comment by PhilippRue** [comment]
try updating your `masci-tools` from which the `kkrparams` class should be imported

**Comment by fBert31** [comment]
I already tried earlier and it didn't solve the problem. But I will doublecheck again...

**Comment by PhilippRue** [comment]
fixede in commit 243a54e
