### ISSUE TITLE
Bandstructure calculations fail with new `aiida_core` due to `ModificationNotAllowed` error

### ISSUE THREAD

**Issue by fBert31** [JuDFTteam/aiida-kkr#16]
When running the band structure mode of the `kkr.kkr` calculation (`if found_kpath`) the calculations can't be submitted since the call of `update_params_wf` raises an error somehow. This `ModificationNotAllowed` error is present for `aiida_core=1.0.0a4` and later. The error message for this calculation with `RUNOPT=qdos` is:
```
(test_jup_env) mb-bert:~ bert$ verdilog 23332
*** 23332 [Bandstructure calc for BiSbTe3 bulk]: TOSUBMIT
*** Scheduler output: N/A
*** Scheduler errors: N/A
*** 1 LOG MESSAGES:
+-> REPORT at 2018-12-18 12:08:40.134797+00:00
 | [23332|JobProcess_aiida_kkr.calculations.kkr:KkrCalculation|on_except]: Traceback (most recent call last):
 |   File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/process_states.py", line 228, in execute
 |     result = self.run_fn(*self.args, **self.kwargs)
 |   File "/Users/bert/sourcecodes/github/aiida_core/aiida/work/job_processes.py", line 632, in run
 |     calc_info, script_filename = self.calc._presubmit(folder, use_unstored_links=False)
 |   File "/Users/bert/sourcecodes/github/aiida_core/aiida/orm/implementation/general/calculation/job/__init__.py", line 1792, in _presubmit
 |     calcinfo = self._prepare_for_submission(folder, inputdict)
 |   File "/Users/bert/sourcecodes/github/aiida-kkr/aiida_kkr/calculations/kkr.py", line 374, in _prepare_for_submission
 |     parameters = update_params_wf(parameters, new_params_node)
 |   File "/Users/bert/sourcecodes/github/aiida_core/aiida/work/workfunctions.py", line 76, in wrapped_function
 |     result, _ = run_get_node(*args, **kwargs)
 |   File "/Users/bert/sourcecodes/github/aiida_core/aiida/work/workfunctions.py", line 68, in run_get_node
 |     proc = process_class(inputs=inputs, runner=runner)
 |   File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/base/state_machine.py", line 188, in __call__
 |     inst.transition_to(inst.create_initial_state())
 |   File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/base/state_machine.py", line 329, in transition_to
 |     *sys.exc_info()[1:])
 |   File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/base/state_machine.py", line 342, in transition_failed
 |     raise_(type(exception), exception, trace)
 |   File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/base/state_machine.py", line 311, in transition_to
 |     self._enter_next_state(new_state)
 |   File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/base/state_machine.py", line 376, in _enter_next_state
 |     self._fire_state_event(StateEventHook.ENTERING_STATE, next_state)
 |   File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/base/state_machine.py", line 290, in _fire_state_event
 |     callback(self, hook, state)
 |   File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/processes.py", line 281, in <lambda>
 |     lambda _s, _h, state: self.on_entering(state))
 |   File "/Users/bert/sourcecodes/github/aiida_core/aiida/work/processes.py", line 224, in on_entering
 |     super(Process, self).on_entering(state)
 |   File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/processes.py", line 594, in on_entering
 |     call_with_super_check(self.on_create)
 |   File "/Users/bert/.virtualenvs/test_jup_env/lib/python2.7/site-packages/plumpy/base/utils.py", line 29, in call_with_super_check
 |     fn(*args, **kwargs)
 |   File "/Users/bert/sourcecodes/github/aiida_core/aiida/work/processes.py", line 113, in on_create
 |     self._pid = self._create_and_setup_db_record()
 |   File "/Users/bert/sourcecodes/github/aiida_core/aiida/work/processes.py", line 353, in _create_and_setup_db_record
 |     self._setup_db_record()
 |   File "/Users/bert/sourcecodes/github/aiida_core/aiida/work/processes.py", line 752, in _setup_db_record
 |     super(FunctionProcess, self)._setup_db_record()
 |   File "/Users/bert/sourcecodes/github/aiida_core/aiida/work/processes.py", line 452, in _setup_db_record
 |     self.calc.add_link_from(parent_calc, 'CALL', link_type=LinkType.CALL)
 |   File "/Users/bert/sourcecodes/github/aiida_core/aiida/orm/implementation/general/calculation/__init__.py", line 582, in add_link_from
 |     return super(AbstractCalculation, self).add_link_from( src, label, link_type)
 |   File "/Users/bert/sourcecodes/github/aiida_core/aiida/orm/mixins.py", line 161, in add_link_from
 |     super(Sealable, self).add_link_from(src, label=label, link_type=link_type)
 |   File "/Users/bert/sourcecodes/github/aiida_core/aiida/orm/implementation/general/node.py", line 616, in add_link_from
 |     src._linking_as_output(self, link_type)
 |   File "/Users/bert/sourcecodes/github/aiida_core/aiida/orm/implementation/general/calculation/job/__init__.py", line 290, in _linking_as_output
 |     valid_states, self.get_state()))
 | ModificationNotAllowed: Can add an output node to a calculation only if it is in one of the following states: [u'SUBMITTING', u'RETRIEVING', u'PARSING'], it is instead TOSUBMIT
```

**Comment by fBert31** [comment]
This problem get's now bypassed by just not calling the `update_params_wf` (commits: `aiida_kkr -> 63575be4b32c4782ae4d0dc09911721eabd190a3` and `masci_tools -> 06ba1889617273a7de1fb0e75af79a90ad861f22`. However, this is not a proper solution to the problem. The suspicion is that the problem is somehow related to `aiida_core` in general.

**Comment by PhilippRue** [comment]
This is working now.
